In [5]:
import yfinance as yf

# Define the ticker symbols for the companies you want to analyze
ticker_symbols = [
    # Banking and Finance
    'HDFCBANK.NS',
    'ICICIBANK.NS',
    'AXISBANK.NS',
    
    # Automobile
    'MARUTI.NS',
    'BAJAJ-AUTO.NS',
    'HEROMOTOCO.NS',
    
    # Information Technology
    'TCS.NS',
    'WIPRO.NS',
    'TECHM.NS',
    
    # Energy
    'ONGC.NS',
    'BPCL.NS',
    
    # Pharmaceuticals
    'SUNPHARMA.NS',
    'DRREDDY.NS',
    'CIPLA.NS',
    
    # Consumer Goods
    'HINDUNILVR.NS',
    'ITC.NS',
    'NESTLEIND.NS',
    
    # Telecommunications
    'BHARTIARTL.NS',
    'IDEA.NS',
    
    # Utilities
    'NTPC.NS',
    'POWERGRID.NS',
    'TATAPOWER.NS',
    
    # Cement
    'ULTRACEMCO.NS',
    'AMBUJACEM.NS',
    'SHREECEM.NS',
    
    # Metals and Mining
    'TATASTEEL.NS',
    'HINDALCO.NS',
    'VEDL.NS'
]

# Fetch historical data
stock_data = yf.download(ticker_symbols, start='2020-01-01', end='2023-1-31')

[*********************100%%**********************]  28 of 28 completed

In [6]:
# Save the stock data to a CSV file
stock_data.to_csv('stock_data.csv')

In [15]:
stock_data

,"('Adj Close', 'AMBUJACEM.NS')_Stock","('Adj Close', 'AXISBANK.NS')_Stock","('Adj Close', 'BAJAJ-AUTO.NS')_Stock","('Adj Close', 'BHARTIARTL.NS')_Stock","('Adj Close', 'BPCL.NS')_Stock","('Adj Close', 'CIPLA.NS')_Stock","('Adj Close', 'DRREDDY.NS')_Stock","('Adj Close', 'HDFCBANK.NS')_Stock","('Adj Close', 'HEROMOTOCO.NS')_Stock","('Adj Close', 'HINDALCO.NS')_Stock",...,NTPC.NS,POWERGRID.NS,TATAPOWER.NS,ULTRACEMCO.NS,AMBUJACEM.NS,SHREECEM.NS,TATASTEEL.NS,HINDALCO.NS,VEDL.NS,Sector
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-01,174.539383,746.027283,2640.764893,447.652802,389.949890,462.176941,2775.076416,1244.189819,2144.578857,208.457291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-02,181.937378,754.247925,2616.369629,449.529144,386.697968,459.846161,2761.101562,1252.120361,2141.845703,214.147766,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,180.209717,740.297852,2575.334473,449.430359,383.485748,456.398590,2779.413330,1234.264282,2144.402832,210.548660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,174.450806,720.668152,2546.496338,444.048279,372.104095,453.290833,2774.546387,1207.552856,2087.802979,203.593597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,176.311386,723.159241,2546.747803,439.554962,365.639984,455.087524,2779.702393,1226.674072,2070.082275,203.155869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-23,495.316315,930.785156,3407.178467,769.166870,345.743958,1045.352417,4304.190430,1654.130615,2673.974121,490.994049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-24,493.191162,908.331360,3466.369629,772.103394,345.101135,1044.958862,4219.750977,1676.276611,2671.372070,481.505981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-25,454.888397,890.517944,3495.424316,772.949463,342.925385,1018.494263,4168.353027,1629.957886,2683.997070,485.927124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-27,376.058868,871.956116,3701.676514,770.958618,332.837891,1030.300049,4280.525391,1597.480347,2636.918457,475.892639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-30,383.027496,870.059998,3611.784912,766.678284,331.403900,1017.658081,4295.210449,1595.848999,2604.296143,469.285767,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import pandas as pd

# Create a DataFrame with the ticker symbols as columns
sector_mapping = pd.DataFrame(columns=ticker_symbols)

# Add the 'Sector' column to the sector_mapping DataFrame
sector_mapping['Sector'] = [
    'Automobile', 'Energy', 'Information Technology',
    'Banking and Finance', 'Banking and Finance', 'Banking and Finance',
    'Automobile', 'Automobile', 'Automobile',
    'Information Technology', 'Information Technology', 'Information Technology',
    'Energy', 'Energy',
    'Pharmaceuticals', 'Pharmaceuticals', 'Pharmaceuticals',
    'Consumer Goods', 'Consumer Goods', 'Consumer Goods',
    'Telecommunications', 'Telecommunications',
    'Utilities', 'Utilities', 'Utilities',
    'Cement', 'Cement', 'Cement',
    'Metals and Mining', 'Metals and Mining', 'Metals and Mining'
]

# Merge the sector_mapping DataFrame with the stock_data DataFrame
stock_data = stock_data.join(sector_mapping)

# Now, you can use the 'Sector' column to categorize the data by sector

C:\Users\ingal\AppData\Local\Temp\ipykernel_25908\1891015927.py:22: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (2 levels on the left, 1 on the right)
  stock_data = stock_data.join(sector_mapping)

In [13]:
import pandas as pd

# Create a DataFrame with the ticker symbols as columns
sector_mapping = pd.DataFrame(columns=ticker_symbols)

# Create a dictionary to map tickers to sectors
sector_mapping_dict = {
    'TATAMOTORS.NS': 'Automobile',
    'RELIANCE.NS': 'Energy',
    'INFY.NS': 'Information Technology',
    'HDFCBANK.NS': 'Banking and Finance',
    'ICICIBANK.NS': 'Banking and Finance',
    'AXISBANK.NS': 'Banking and Finance',
    'MARUTI.NS': 'Automobile',
    'BAJAJ-AUTO.NS': 'Automobile',
    'HEROMOTOCO.NS': 'Automobile',
    'TCS.NS': 'Information Technology',
    'WIPRO.NS': 'Information Technology',
    'TECHM.NS': 'Information Technology',
    'ONGC.NS': 'Energy',
    'BPCL.NS': 'Energy',
    'SUNPHARMA.NS': 'Pharmaceuticals',
    'DRREDDY.NS': 'Pharmaceuticals',
    'CIPLA.NS': 'Pharmaceuticals',
    'HINDUNILVR.NS': 'Consumer Goods',
    'ITC.NS': 'Consumer Goods',
    'NESTLEIND.NS': 'Consumer Goods',
    'BHARTIARTL.NS': 'Telecommunications',
    'IDEA.NS': 'Telecommunications',
    'NTPC.NS': 'Utilities',
    'POWERGRID.NS': 'Utilities',
    'TATAPOWER.NS': 'Utilities',
    'ULTRACEMCO.NS': 'Cement',
    'AMBUJACEM.NS': 'Cement',
    'SHREECEM.NS': 'Cement',
    'TATASTEEL.NS': 'Metals and Mining',
    'HINDALCO.NS': 'Metals and Mining',
    'VEDL.NS': 'Metals and Mining'
}


# Add a 'Sector' column to the sector_mapping DataFrame
sector_mapping['Sector'] = sector_mapping.index.map(sector_mapping_dict)

# Rename the columns in the stock_data DataFrame to avoid conflicts
stock_data.columns = [f'{col}_Stock' for col in stock_data.columns]

# Merge the sector_mapping DataFrame with the stock_data DataFrame
stock_data = stock_data.join(sector_mapping)

In [14]:
stock_data

,"('Adj Close', 'AMBUJACEM.NS')_Stock","('Adj Close', 'AXISBANK.NS')_Stock","('Adj Close', 'BAJAJ-AUTO.NS')_Stock","('Adj Close', 'BHARTIARTL.NS')_Stock","('Adj Close', 'BPCL.NS')_Stock","('Adj Close', 'CIPLA.NS')_Stock","('Adj Close', 'DRREDDY.NS')_Stock","('Adj Close', 'HDFCBANK.NS')_Stock","('Adj Close', 'HEROMOTOCO.NS')_Stock","('Adj Close', 'HINDALCO.NS')_Stock",...,NTPC.NS,POWERGRID.NS,TATAPOWER.NS,ULTRACEMCO.NS,AMBUJACEM.NS,SHREECEM.NS,TATASTEEL.NS,HINDALCO.NS,VEDL.NS,Sector
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-01,174.539383,746.027283,2640.764893,447.652802,389.949890,462.176941,2775.076416,1244.189819,2144.578857,208.457291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-02,181.937378,754.247925,2616.369629,449.529144,386.697968,459.846161,2761.101562,1252.120361,2141.845703,214.147766,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,180.209717,740.297852,2575.334473,449.430359,383.485748,456.398590,2779.413330,1234.264282,2144.402832,210.548660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,174.450806,720.668152,2546.496338,444.048279,372.104095,453.290833,2774.546387,1207.552856,2087.802979,203.593597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,176.311386,723.159241,2546.747803,439.554962,365.639984,455.087524,2779.702393,1226.674072,2070.082275,203.155869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-23,495.316315,930.785156,3407.178467,769.166870,345.743958,1045.352417,4304.190430,1654.130615,2673.974121,490.994049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-24,493.191162,908.331360,3466.369629,772.103394,345.101135,1044.958862,4219.750977,1676.276611,2671.372070,481.505981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-25,454.888397,890.517944,3495.424316,772.949463,342.925385,1018.494263,4168.353027,1629.957886,2683.997070,485.927124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-27,376.058868,871.956116,3701.676514,770.958618,332.837891,1030.300049,4280.525391,1597.480347,2636.918457,475.892639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-30,383.027496,870.059998,3611.784912,766.678284,331.403900,1017.658081,4295.210449,1595.848999,2604.296143,469.285767,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN